local config_path = vim.fn.stdpath('config')

vim.keymap.set({'n', 'x'}, '<leader>ff', '<cmd>FzfLua files<cr>', { silent = true, desc = 'Find Files' })
vim.keymap.set({'n', 'x'}, '<leader>fo', '<cmd>FzfLua oldfiles<cr>', { silent = true, desc = 'Find Old Files' })
vim.keymap.set({'n', 'x'}, '<leader>fq', '<cmd>FzfLua quickfix<cr>', { silent = true, desc = 'Quickfix List' })
vim.keymap.set({'n', 'x'}, '<leader>fb', '<cmd>FzfLua buffers<cr>', { silent = true, desc = 'Find Buffers' })
vim.keymap.set({'n', 'x'}, '<leader>fg', '<cmd>FzfLua live_grep<cr>', { silent = true, desc = 'Live Grep' })
vim.keymap.set({'n', 'x'}, '<leader>flc', '<cmd>FzfLua lgrep_curbuf<cr>', { silent = true, desc = 'Live Grep Current Buffer' })
vim.keymap.set({'n', 'x'}, '<leader>fc', '<cmd>FzfLua files cwd=' .. config_path .. '<cr>', { silent = true, desc = 'Find Config Directory' })
vim.keymap.set({'n', 'x'}, '<leader>fh', '<cmd>FzfLua helptags<cr>', { silent = true, desc = 'Find Helptags' })
vim.keymap.set({'n', 'x'}, '<leader>f:', '<cmd>FzfLua commands<cr>', { silent = true, desc = 'Find Commands' })
vim.keymap.set({'n', 'x'}, '<leader>fj', '<cmd>FzfLua jumps<cr>', { silent = true, desc = 'Find Jumps' })
vim.keymap.set({'n', 'x'}, '<leader>fm', '<cmd>FzfLua marks<cr>', { silent = true, desc = 'Find Marks' })
vim.keymap.set({'n', 'x'}, '<leader>fxt', '<cmd>FzfLua colorschemes<cr>', { silent = true, desc = 'Find Themes' })
vim.keymap.set({'n', 'x'}, '<leader>gc', '<cmd>FzfLua live_grep cwd=' .. config_path .. '<cr>', { silent = true, desc = 'Grep Config' })
vim.keymap.set({'n', 'x'}, '<leader>fld', '<cmd>FzfLua lsp_document_diagnostics<cr>', { silent = true, desc = 'Find Diagnostics' })
vim.keymap.set({'n', 'x'}, '<leader>f*', '<cmd>FzfLua lsp_finder<cr>', { silent = true, desc = 'Find Symbol' })
vim.keymap.set({'n', 'x'}, '<leader>ft', '<cmd>FzfLua lsp_typedefs<cr>', { silent = true, desc = 'Find Typedefs' })
vim.keymap.set({'n', 'x'}, '<leader>fsd', '<cmd>FzfLua lsp_document_symbols<cr>', { silent = true, desc = 'Find Document Symbols' })
vim.keymap.set({'n', 'x'}, '<leader>fsw', '<cmd>FzfLua lsp_workspace_symbols<cr>', { silent = true, desc = 'Find Workspace Symbols' })
vim.keymap.set({'n', 'x'}, '<leader>fd', '<cmd>FzfLua lsp_definitions<cr>', { silent = true, desc = 'Find Definitions' })
vim.keymap.set({'n', 'x'}, '<leader>fD', '<cmd>FzfLua lsp_declarations<cr>', { silent = true, desc = 'Find Declarations' })
vim.keymap.set({'n', 'x'}, '<leader>ca', '<cmd>FzfLua lsp_code_actions<cr>', { silent = true, desc = 'Code Actions' })
vim.keymap.set({'n', 'x'}, '<leader>fxic', '<cmd>FzfLua lsp_incoming_calls<cr>', { silent = true, desc = 'Find Incoming Calls' })
vim.keymap.set({'n', 'x'}, '<leader>fxoc', '<cmd>FzfLua lsp_outgoing_calls<cr>', { silent = true, desc = 'Find Outgoing Calls' })
vim.keymap.set({'n', 'x'}, '<leader>fk', '<cmd>FzfLua keymaps<cr>', { silent = true, desc = 'Find Keymaps' })
