larp.fn.map('n', '<leader>no', '<cmd>Neorg<CR>', { noremap = true, silent = true })
larp.fn.map('n', '<leader>nw', function()
    vim.ui.select({ 'default', 'notes' }, { prompt = 'Workspace: ' }, function(input)
        vim.cmd('Neorg workspace ' .. input)
    end)
end, { noremap = true, silent = true })
