require('todo-comments').setup({})
vim.keymap.set('n', ']t', function()
    require('todo-comments').jump_next()
end, { desc = 'Next todo comment', silent = true })
vim.keymap.set('n', '[t', function()
    require('todo-comments').jump_prev()
end, { desc = 'Previous todo comment', silent = true })
-- You can also specify a list of valid jump keywords
vim.keymap.set('n', ']t', function()
    require('todo-comments').jump_next({ keywords = { 'ERROR', 'WARNING' } })
end, { desc = 'Next error/warning todo comment', silent = true })
