vim.keymap.set("n", "<leader>ff", "<cmd>FzfLua files<cr>", {silent = true, desc = "Find Files"})
vim.keymap.set("n", "<leader>fo", "<cmd>FzfLua oldfiles<cr>", {silent = true, desc = "Find Old Files"})
vim.keymap.set("n", "<leader>fq", "<cmd>FzfLua quickfix<cr>", {silent = true, desc = "Quickfix List"})
vim.keymap.set("n", "<leader>fb", "<cmd>FzfLua buffers<cr>", {silent = true, desc = "Find Buffers"})
vim.keymap.set("n", "<leader>fng", "<cmd>FzfLua grep<cr>", {silent = true, desc = "Grep"})
vim.keymap.set("n", "<leader>flg", "<cmd>FzfLua live_grep<cr>", {silent = true, desc = "Live Grep"})
vim.keymap.set("n", "<leader>flc", "<cmd>FzfLua lgrep_curbuf<cr>", {silent = true, desc = "Live Grep Current Buffer"})
vim.keymap.set("n", "<leader>fc",  "<cmd>FzfLua files cwd=~/.config/nvim<cr>",{silent = true, desc = "Find Config Directory"})
